services:
  - type: web
    name: porteytenenciaprogresando
    runtime: php  # <--- ESTA ES LA LÃNEA CLAVE QUE DEBES CAMBIAR
    plan: free
    buildCommand: |
      composer install --no-dev --optimize-autoloader
      php artisan key:generate
      php artisan config:cache
      php artisan route:cache
    startCommand: php artisan serve --host=0.0.0.0 --port=$PORT
